include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

stages:
  - test
  - deploy

code_quality:
  tags:
    - docker
  artifacts:
    paths: [gl-code-quality-report.json]

sast:
  tags:
    - docker
  artifacts:
    paths: [gl-sast-report.json]

jest:
  image: node:10
  stage: test
  before_script:
    - yarn install
  script:
    - yarn build
    - yarn test --coverage
  when: on_success

deploy-development:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  stage: deploy
  environment: development
  variables:
    GIT_URL: git@$REMOTE_SERVER:sizakat-5.0-frontend.git
  before_script:
    - mkdir ~/.ssh
    - cat "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - mv "$KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git config remote.development.url >&- || git remote add development $GIT_URL
    - git checkout $CI_COMMIT_TAG
    - git push --force development $CI_COMMIT_TAG 2>&1 | tee git-push.log
    - >-
      grep 'Everything up-to-date' git-push.log ||
      "$(grep -E 'remote: Return with exit [0-9]+' git-push.log | grep -oE 'exit [0-9]+')"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development-\d+$/'

deploy-testing:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  stage: deploy
  environment: testing
  variables:
    GIT_URL: git@$REMOTE_SERVER:sizakat-5.0-frontend.git
  before_script:
    - mkdir ~/.ssh
    - cat "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - mv "$KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git config remote.testing.url >&- || git remote add testing $GIT_URL
    - git checkout $CI_COMMIT_BRANCH && git merge
    - git push testing $CI_COMMIT_BRANCH 2>&1 | tee git-push.log
    - "$(grep -E 'remote: Return with exit [0-9]+' git-push.log | grep -oE 'exit [0-9]+')"
  rules:
    - if: '$CI_COMMIT_BRANCH == "testing"'
